---
apiVersion: imgpkg.carvel.dev/v1alpha1
images:
- annotations:
    kbld.carvel.dev/id: grafana/grafana:7.5.17
    kbld.carvel.dev/origins: |
      - resolved:
          tag: 7.5.17
          url: grafana/grafana:7.5.17
  image: index.docker.io/grafana/grafana@sha256:15abb652aa82eeb9f45589278b34ae6ef0e96f74c389cadde31831eb0b1ce228
- annotations:
    kbld.carvel.dev/id: kiwigrid/k8s-sidecar:1.15.6
    kbld.carvel.dev/origins: |
      - resolved:
          tag: 1.15.6
          url: kiwigrid/k8s-sidecar:1.15.6
  image: index.docker.io/kiwigrid/k8s-sidecar@sha256:1f025ae37b7b20d63bffd179e5e6f972039dd53d9646388c0a8c456229c7bbcb
kind: ImagesLock
