apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: kapp-controller.community.tanzu.vmware.com.0.28.0
spec:
  refName: kapp-controller.community.tanzu.vmware.com
  version: 0.28.0
  releaseNotes: "kapp-controller 0.28.0 https://github.com/vmware-tanzu/carvel-kapp-controller"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/kapp-controller@sha256:ee2c6af40080c1e734e2d6fd4bab244c984ba15be29009c2319c18d7d77c7f1c
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
